version: "3.9"

services:

  app:
    build: .
    container_name: blog_app
    restart: unless-stopped
    working_dir: /app
    ports:
      - "5001:5000"
    environment:
      MONGO_URI: ${MONGO_URI}
      UPSTASH_REDIS_URL: ${UPSTASH_REDIS_URL}
      UPSTASH_REDIS_TOKEN: ${UPSTASH_REDIS_TOKEN}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
